# Generated by Django 4.0.3 on 2022-03-25 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extrat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonRetour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bon_retour', models.CharField(default='', max_length=50)),
                ('date_bon_retour', models.DateField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.agence')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.client')),
            ],
        ),
        migrations.CreateModel(
            name='BonSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bon_sortie', models.CharField(default='', max_length=50)),
                ('date_bon_sortie', models.DateField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.agence')),
            ],
        ),
        migrations.CreateModel(
            name='BonTransfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bon_transfert', models.CharField(default='', max_length=50)),
                ('date_bon_transfert', models.DateField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agence_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_agence_destination', to='extrat.agence')),
                ('agence_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_agence_source', to='extrat.agence')),
            ],
        ),
        migrations.CreateModel(
            name='BonTransfertExterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bon_transfert_externe', models.CharField(default='', max_length=50)),
                ('date_bon_transfert_externe', models.DateField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agence_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ext_agence_destination', to='extrat.agence')),
                ('agence_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ext_agence_source', to='extrat.agence')),
            ],
        ),
        migrations.CreateModel(
            name='BonTransfertInterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bon_transfert_interne', models.CharField(default='', max_length=50)),
                ('date_preparation', models.DateField()),
                ('date_bon_transfert_interne', models.DateField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agence_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='int_agence_destination', to='extrat.agence')),
                ('agence_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='int_agence_source', to='extrat.agence')),
            ],
        ),
        migrations.CreateModel(
            name='BonTransfertInterneExterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bon_transfert_interne_externe', models.CharField(default='', max_length=50)),
                ('date_bon_transfert_interne_externe', models.DateField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agence_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='extrat.agence')),
                ('agence_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='extrat.agence')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('qte_init', models.IntegerField(default=0)),
                ('qte_min', models.IntegerField(default=0)),
                ('qte_max', models.IntegerField(default=0)),
                ('qte_stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.agence')),
            ],
        ),
        migrations.CreateModel(
            name='TypeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.agence')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitUnite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_unitaire', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.produit')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.unite')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='type_produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.typeproduit'),
        ),
        migrations.CreateModel(
            name='LigneBonTransfertInterne_Externe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_bon_transfert_interne_externe', models.IntegerField(default=0)),
                ('qte_livree', models.IntegerField(default=0)),
                ('qte_restante', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bon_transfert_interne_externe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.bontransfertinterneexterne')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.produit')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.unite')),
            ],
        ),
        migrations.CreateModel(
            name='LigneBonTransfertExterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_bon_transfert_externe', models.IntegerField(default=0)),
                ('qte_livree', models.IntegerField(default=0)),
                ('qte_restante', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bon_transfert_externe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.bontransfertexterne')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.produit')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.unite')),
            ],
        ),
        migrations.CreateModel(
            name='LigneBonTransfert_Interne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_bon_transfert_interne', models.IntegerField(default=0)),
                ('qte_livree', models.IntegerField(default=0)),
                ('qte_restante', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bon_transfert_interne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.bontransfertinterne')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.produit')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.unite')),
            ],
        ),
        migrations.CreateModel(
            name='LigneBonTransfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_bon_transfert', models.IntegerField(default=0)),
                ('qte_livree', models.IntegerField(default=0)),
                ('qte_restante', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bon_transfert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.bontransfert')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.produit')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.unite')),
            ],
        ),
        migrations.CreateModel(
            name='LigneBonSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_bon_sortie', models.IntegerField(default=0)),
                ('qte_livree', models.IntegerField(default=0)),
                ('qte_restante', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bon_sortie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.bonsortie')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.produit')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.unite')),
            ],
        ),
        migrations.CreateModel(
            name='LigneBonRetour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_bon_retour', models.IntegerField(default=0)),
                ('qte_livree', models.IntegerField(default=0)),
                ('qte_restante', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bon_retour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.bonretour')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.produit')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.unite')),
            ],
        ),
        migrations.CreateModel(
            name='FournisseurProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_unitaire', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.produit')),
            ],
        ),
    ]
