# Generated by Django 4.0.3 on 2022-03-25 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extrat', '0001_initial'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_approvisionnement', models.CharField(max_length=50, unique=True)),
                ('date_approvisionnement', models.DateField()),
                ('date_reception', models.DateField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.agence')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.fournisseur')),
                ('tva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.tva')),
            ],
        ),
        migrations.CreateModel(
            name='BonDeReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bon_reception', models.CharField(max_length=50, unique=True)),
                ('date_bon_reception', models.DateField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.agence')),
                ('approvisionnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approvisionnement.approvisionnement')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.fournisseur')),
                ('tva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.tva')),
            ],
        ),
        migrations.CreateModel(
            name='LigneBonDeReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_commandee', models.IntegerField()),
                ('qte_recue', models.IntegerField()),
                ('qte_restante', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bon_de_reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approvisionnement.bondereception')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.produit')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.unite')),
            ],
        ),
        migrations.CreateModel(
            name='LigneApprovisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approvisionnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approvisionnement.approvisionnement')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.produit')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.unite')),
            ],
        ),
    ]
