# Generated by Django 4.0.3 on 2022-03-25 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extrat', '0001_initial'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bon_livraison', models.CharField(default='', max_length=50)),
                ('date_bon_livraison', models.DateField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.agence')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.client')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_commande', models.CharField(default='', max_length=50)),
                ('date_commande', models.DateField()),
                ('date_livraison', models.DateField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.agence')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.client')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_facture', models.CharField(default='', max_length=50)),
                ('date_facture', models.DateField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.agence')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.client')),
            ],
        ),
        migrations.CreateModel(
            name='TypeFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.agence')),
            ],
        ),
        migrations.CreateModel(
            name='TypeCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.agence')),
            ],
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_facture', models.IntegerField(default=0)),
                ('qte_livree', models.IntegerField(default=0)),
                ('qte_restante', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commande.facture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.produit')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_commande', models.IntegerField(default=0)),
                ('qte_livree', models.IntegerField(default=0)),
                ('qte_restante', models.IntegerField(default=0)),
                ('prix_unitaire', models.IntegerField(default=0)),
                ('prix_total', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commande.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.produit')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.unite')),
            ],
        ),
        migrations.CreateModel(
            name='LigneBonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_unitaire', models.IntegerField(default=0)),
                ('qte_bon_livraison', models.IntegerField(default=0)),
                ('qte_livree', models.IntegerField(default=0)),
                ('qte_restante', models.IntegerField(default=0)),
                ('prix_total', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bon_livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commande.bonlivraison')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.produit')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extrat.unite')),
            ],
        ),
        migrations.AddField(
            model_name='facture',
            name='type_facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commande.typefacture'),
        ),
        migrations.AddField(
            model_name='commande',
            name='type_commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commande.typecommande'),
        ),
    ]
